Repository stackhpc/stackhpc-release-train, pull requests merged in 2022-08, with the labels that each got.

#71 Add `codeowners` to all repositories defined within `source_repositories`
  ansible/inventory/group_vars/all/source-repositories
Labels: enhancement

#86 Statefile fixes
  terraform/github/.terraform.lock.hcl
  terraform/github/import_resources.py
  terraform/github/provider.tf
Labels: bug, enhancement

#104 feat: automatic update of community files main
  .github/CODEOWNERS
Labels: stackhpc-ci, community-files

#111 feat: add documentation about `terraform github`
  docs/usage/github-organisation-management.md
  mkdocs.yml
Labels: documentation
